services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5194:5194"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5194